### Part 1 Tensors

In [64]:
import torch
import numpy as np

#### Initializing tensors:
##### Method 1: Directly from data

In [65]:
simple_list = [[1,2], [2,4]]
simple_list

[[1, 2], [2, 4]]

In [66]:
simple_list = torch.tensor(simple_list)
simple_list

tensor([[1, 2],
        [2, 4]])

##### Method 2: Going from np array to tensor and  vice versa

In [67]:
np_data = np.array([[1,2], [2,4]])
np_data

array([[1, 2],
       [2, 4]])

This will retain the np properties, like dtype or shape

In [68]:
x = torch.from_numpy(np_data)
x

tensor([[1, 2],
        [2, 4]], dtype=torch.int32)

In [69]:
print(x.dtype)
print(x.shape)

torch.int32
torch.Size([2, 2])


Even if we change the actual values the np properties will be retained

In [70]:
y = torch.ones_like(x)
y

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

If we want to overwrite this we can:

In [71]:
z = torch.rand_like(x, dtype = torch.float)
z

tensor([[0.7044, 0.1454],
        [0.7153, 0.9423]])

In [72]:
print(z.dtype)
print(z.shape)

torch.float32
torch.Size([2, 2])


##### Method 3: From another tensor

In [73]:
shape = (2,3,)
torch.rand(shape)

tensor([[0.7709, 0.9861, 0.1341],
        [0.3277, 0.9959, 0.9150]])

In [74]:
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [75]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [76]:
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [77]:
torch.cuda.is_available()

False

In [78]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

#### Tensor operations

NumPy like operations

In [79]:
tensor

tensor([[0.2543, 0.2066, 0.2495, 0.2001],
        [0.7687, 0.6524, 0.9899, 0.6351],
        [0.5903, 0.4982, 0.7260, 0.7534]])

In [80]:
tensor[0]

tensor([0.2543, 0.2066, 0.2495, 0.2001])

In [81]:
tensor[-1]

tensor([0.5903, 0.4982, 0.7260, 0.7534])

In [82]:
tensor[:,0]

tensor([0.2543, 0.7687, 0.5903])

In [83]:
tensor[:,1] = 0
tensor

tensor([[0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534]])

In [84]:
torch.cat([tensor, tensor])

tensor([[0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534],
        [0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534]])

In [85]:
torch.cat([tensor, tensor], dim = 1)

tensor([[0.2543, 0.0000, 0.2495, 0.2001, 0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351, 0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534, 0.5903, 0.0000, 0.7260, 0.7534]])

##### Matrix multiplication

To perform matrix multiplication, the first matrix must have the same number of columns as the second matrix has rows. The number of rows of the resulting matrix equals the number of rows of the first matrix, and the number of columns of the resulting matrix equals the number of columns of the second matrix.

👉 https://en.wikipedia.org/wiki/Matrix_multiplication

In [86]:
tensor.shape

torch.Size([3, 4])

In [87]:
tensor.T.shape

torch.Size([4, 3])

In [88]:
tensor

tensor([[0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534]])

In [89]:
tensor.T

tensor([[0.2543, 0.7687, 0.5903],
        [0.0000, 0.0000, 0.0000],
        [0.2495, 0.9899, 0.7260],
        [0.2001, 0.6351, 0.7534]])

In [90]:
# Use the .matmul attribute of a tensor object
tensor.matmul(tensor.T)

tensor([[0.1670, 0.5696, 0.4821],
        [0.5696, 1.9742, 1.6510],
        [0.4821, 1.6510, 1.4432]])

In [91]:
# Use .matmul from torch instead
torch.matmul(tensor,tensor.T)

tensor([[0.1670, 0.5696, 0.4821],
        [0.5696, 1.9742, 1.6510],
        [0.4821, 1.6510, 1.4432]])

In [92]:
# Use the " @ " sign which stands from matrix multiplication
tensor @ tensor.T

tensor([[0.1670, 0.5696, 0.4821],
        [0.5696, 1.9742, 1.6510],
        [0.4821, 1.6510, 1.4432]])

In [93]:
# We may also multiply tensors element-wise as long as n rows and n columns match a.k.a. there are of the same dimension
tensor * tensor

tensor([[0.0647, 0.0000, 0.0623, 0.0400],
        [0.5910, 0.0000, 0.9799, 0.4033],
        [0.3485, 0.0000, 0.5271, 0.5676]])

In [94]:
# Element wise multiplication can also be done by the .mul attribute of a tensor or of torch
print(tensor.mul(tensor))
print(torch.mul(tensor, tensor)) 

tensor([[0.0647, 0.0000, 0.0623, 0.0400],
        [0.5910, 0.0000, 0.9799, 0.4033],
        [0.3485, 0.0000, 0.5271, 0.5676]])
tensor([[0.0647, 0.0000, 0.0623, 0.0400],
        [0.5910, 0.0000, 0.9799, 0.4033],
        [0.3485, 0.0000, 0.5271, 0.5676]])


Same for +, -, / do element wise operations

In [95]:
# Sum elements in tensor, which will return a one element tensor
tensor.sum()

tensor(5.1674)

In [96]:
# If we want the sum to be returned into a python numeric we can call the .item attribute
tensor.sum().item()

5.167440891265869

The attribute operations give out an output but do not modify the tensor itself unless we assign it with the " = " explicitly. We can see this in the example 3 chunks of code below 

In [97]:
tensor.add(3)

tensor([[3.2543, 3.0000, 3.2495, 3.2001],
        [3.7687, 3.0000, 3.9899, 3.6351],
        [3.5903, 3.0000, 3.7260, 3.7534]])

In [98]:
tensor

tensor([[0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534]])

In [99]:
tensor = tensor.add(3)
tensor

tensor([[3.2543, 3.0000, 3.2495, 3.2001],
        [3.7687, 3.0000, 3.9899, 3.6351],
        [3.5903, 3.0000, 3.7260, 3.7534]])

There is another way to do this, using the " _ " after the attribute. In the chunk below we add another 3 to each element of the same tensor without using the " = " sign. **NOTE:** generally the use of " _ " is discouraged because it deletes the history and can be problematic in some cases

In [100]:
tensor.add_(3)
tensor

tensor([[6.2543, 6.0000, 6.2495, 6.2001],
        [6.7687, 6.0000, 6.9899, 6.6351],
        [6.5903, 6.0000, 6.7260, 6.7534]])

NumPy arrays based on tensors stay connected, which saves computational space. In the three chunks below we create an np.array based on a tensor, then change only the tensor, but then we see that the change has also been applied to the NumPy array  

In [102]:
n = tensor.numpy()
n

array([[6.2543445, 6.       , 6.249512 , 6.2001143],
       [6.768735 , 6.       , 6.9899144, 6.6350904],
       [6.590308 , 6.       , 6.726021 , 6.753401 ]], dtype=float32)

In [103]:
tensor.sub_(6)

tensor([[0.2543, 0.0000, 0.2495, 0.2001],
        [0.7687, 0.0000, 0.9899, 0.6351],
        [0.5903, 0.0000, 0.7260, 0.7534]])

In [104]:
n

array([[0.25434446, 0.        , 0.2495122 , 0.20011425],
       [0.76873493, 0.        , 0.9899144 , 0.63509035],
       [0.5903082 , 0.        , 0.7260208 , 0.7534008 ]], dtype=float32)

In [116]:
# This works vice versa

n = np.ones((3 , 4))
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:

tensor = torch.from_numpy(n)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [119]:
n = np.add(n, 0.35, out = n)
n

array([[1.35, 1.35, 1.35, 1.35],
       [1.35, 1.35, 1.35, 1.35],
       [1.35, 1.35, 1.35, 1.35]])

In [120]:
tensor

tensor([[1.3500, 1.3500, 1.3500, 1.3500],
        [1.3500, 1.3500, 1.3500, 1.3500],
        [1.3500, 1.3500, 1.3500, 1.3500]], dtype=torch.float64)

#### Pytorch profiler

To check the runtime of your code

In [122]:
tensor = torch.rand((3,4))
tensor

tensor([[0.8784, 0.5099, 0.8268, 0.0631],
        [0.0167, 0.8509, 0.2363, 0.7816],
        [0.1874, 0.4343, 0.7964, 0.0574]])

In [124]:
with torch.autograd.profiler.profile(use_cpu = True) as prof:
    for _ in range(100):
        y = tensor @ tensor.T

In [125]:
print(prof)

----------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                  Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
----------------------  ------------  ------------  ------------  ------------  ------------  ------------  
         aten::numpy_T         0.23%       4.000us         1.80%      31.000us      31.000us             1  
         aten::permute         1.10%      19.000us         1.57%      27.000us      27.000us             1  
      aten::as_strided         0.47%       8.000us         0.47%       8.000us       8.000us             1  
          aten::matmul         0.23%       4.000us         1.98%      34.000us      34.000us             1  
              aten::mm         1.74%      30.000us         1.74%      30.000us      30.000us             1  
    aten::resolve_conj         0.00%       0.000us         0.00%       0.000us       0.000us             1  
    aten::resolve_c